CREATE TABLE `plugin_ocr_cache` (
	`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`md5` CHAR(32) NULL DEFAULT NULL COMMENT '源MD5摘要',
	`value` CHAR(20) NULL DEFAULT NULL COMMENT 'OCR 后的值',
	`create_time` DATETIME NULL DEFAULT NULL COMMENT '添加时间',
	PRIMARY KEY (`id`)
)
COMMENT='OCR 缓存表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
